### ISSUE TITLE
Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by sibelius** [WaTech/servicenowrest#2]
I'm receiving this error:

Hostname/IP doesn't match certificate's altnames: "Host: demo.servicenow.com. is not in the cert's altnames: DNS:*.service-now.com, DNS:service-now.com

I'm using node v4.1.1

anyone know how to fix it?

**Comment by jasontmckee** [comment]
The demo.servicenow.com is just for example, you'll want to change the instance/username/password in the config object to match your instance/environment.

**Comment by sibelius** [comment]
@jasontmckee is there a demo or test instance of servicenow available to anyone?

thanks

**Comment by justinb26** [comment]
Jason actually got snapped up by service now and works for them now :)

I can answer your question though: you can get free developer instances at
http://developer.servicenow.com

These are full featured, but will be automatically reclaimed if there's no
activity on them for X days

Hope this helps!
-justinb

On Oct 7, 2015, at 11:09 AM, Sibelius Seraphini notifications@github.com
wrote:

@jasontmckee https://github.com/jasontmckee is there a demo or test
instance of servicenow available to anyone?

thanks

**Comment by sibelius** [comment]
@justinb26 thanks
